# Site settings
title: SNARC Consulting
header-img: img/home-bg.jpg
email: sales@snarc.com
copyright_name: SNARC Consulting Limited
company_number: 10623724
description: "Description"
baseurl: ""
url: "http://www.snarc.com"
#twitter_username: ""
#github_username: ""
#facebook_username: ""
email_username:  sales@snarc.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
collections:
  profiles:
    output: true
    permalink: /about/:title

defaults:
  - scope:
      path: ""
      type: profiles
    values:
      layout: profile
